name: Build Release

on:
  pull_request:
    branches:
      - 'release/**'
      - 'release'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{secrets.SUBMODULE_TOKEN}}
          submodules: recursive

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Set up secret Key
        shell: bash
        env:
          LOCAL_PROPERTIES: ${{secrets.LOCAL_PROPERTIES}}
          GOOGLE_SERVICES_JSON: ${{secrets.GOOGLE_SERVICES_JSON}}
        run: |
          touch local.properties
          echo $LOCAL_PROPERTIES > local.properties
          touch app/google-services.json
          echo $GOOGLE_SERVICES_JSON > app/google-services.json

      - name: Assemble Library
        run: |
          ./gradlew :common:assemble
          ./gradlew :data:assemble
          ./gradlew :domain:assemble
          ./gradlew :remote:assemble

      - name: Assemble Debug
        run: |
          ./gradlew assembleDebug

      - name: Test Library
        run: |
          ./gradlew :common:test
          ./gradlew :data:test
          ./gradlew :domain:test
          ./gradlew :remote:test

      - name: Test Debug
        run: ./gradlew testDebug

